points:
  zones:
    matrix:
      anchor:
        rotate: 5
      columns:
        pinky:
          key:
            spread: 19
            rows:
              bottom:
                column_net: P21
              home:
                column_net: P20
        ring:
          key:
            spread: 19
            splay: -5
            origin: [-13, -19]
            stagger: 10
            rows:
              bottom:
                column_net: P19
              home:
                column_net: P18
        middle:
          key:
            spread: 19
            stagger: 5
            rows:
              bottom:
                column_net: P15
              home:
                column_net: P14
        index:
          key:
            spread: 19
            stagger: -6
            rows:
              bottom:
                column_net: P26
              home:
                column_net: P10
        index_far:
          key:
            spread: 19
            stagger: -6
            rows:
              bottom:
                column_net: P26
              home:
                column_net: P10
      rows:
        bottom:
          padding: 19
        home:
          padding: 19
        top:
    thumb:
      anchor:
        ref: matrix_index_bottom
        shift: [3, -35]
        rotate: -6
      columns:
        near:
          key:
            origin: [1,10]
          rows:
            home:
              column_net: P8
        home:

          rows:
            home:
              column_net: P9
          key.spread: 21.25
          key.splay: -13
          key.origin: [-11.75, -9]
        pen:
          key.spread: 21.25
          key.splay: -13
          key.origin: [-9.5, -9]
  key:
    footprints:
      mx:
        type: mx
        nets:
          from: GND
          to: "{{column_net}}"
        params:
          keycaps: true
          reverse: true
          hotswap: false

outlines:
  plate:
    - what: rectangle
      where: true
      asym: source
      size: 22
      corner: 3
    - what: rectangle
      where: true
      asym: source
      size: 14
      bound: false
      operation: subtract
  pcb_perimeter_raw:
    - what: rectangle
      where: true
      asym: source
      size: 18
      corner: 1
  polygon:
    - what: polygon # all borders
      operation: stack
      points:
        - ref: matrix_pinky_bottom
          shift: [-15,-13]
        - ref: matrix_pinky_top
          shift: [-13,0.8u]
        - ref: matrix_middle_top
          shift: [-9,10]
        - ref: matrix_middle_top
          shift: [9,10]
        - ref: matrix_index_top
          shift: [1.45u,9]
        - ref: matrix_index_far_top
          shift: [40.5,9]
        - ref: thumb_pen
          shift: [23,-4]
        - ref: thumb_home_home
          shift: [10,-19]
        - ref: thumb_near_home
          shift: [9,-15]
  pcb_perimeter:
    - what: outline # keys
      name: pcb_perimeter_raw
    - what: outline
      name: polygon
      operation: add
  pcb:
    - what: outline
      name: pcb_perimeter
      fillet: 3

pcbs:
  tiny20:
    outlines:
      main:
        outline: pcb
    footprints:
      keys:
        what: mx
        where: true
        params:
          from: GND
          to: "{{column_net}}"
          keycaps: true
          reverse: true
          hotswap: false
      promicro:
        what: promicro
        where:
          ref: matrix_index_far_top
          shift: [28, -0.5u]
          rotate: -90
        params:
          orientation: down
      trrs:
        what: trrs
        where:
          ref: matrix_index_far_top
          shift: [42, -34]
          rotate: -90
        params:
          A: GND
          B: GND
          C: P1
          D: VCC
          reverse: true
          symmetric: true
